name: Clean logs
run-name: Clean runs logs older than a week

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # every Monday

permissions:
  actions: write

jobs:
 Cleaning:
    runs-on: ubuntu-latest

    steps:
      - uses: igorjs/gh-actions-clean-workflow@v7
        with:
          runs_older_than: 7 
          token: ${{ github.token }}
      - uses: lgmorand/gh-workflow-keepalive@v1
        with:
          time_elapsed: 30
